=== tiwm23tig10/tiwm23tig10/src/jpdata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="japao">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Lugar" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="NomeLugar" type="xs:string"/>
              <xs:element name="Descricao" minOccurs="0">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Imagem" type="xs:anyURI" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== tiwm23tig10/tiwm23tig10/src/jpdata.xml
<?xml version="1.0"?>
<japao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jpdata.xsd">
    <Lugar>
        <NomeLugar>Tokyo</NomeLugar>
        <Descricao>
            Tokyo é a capital do Japão, conhecida por sua mistura única de modernidade e tradição. Fundada como Edo no início do século XVII, tornou-se o centro político do país no final do século XIX. Explore os bairros agitados como Shibuya e desfrute da serenidade nos jardins históricos como o Jardim Rikugien. A culinária diversificada e a arquitetura futurista fazem de Tokyo uma experiência inesquecível.
            <p>Descubra o contraste entre arranha-céus imponentes e templos ancestrais, proporcionando uma visão fascinante da cultura japonesa contemporânea e histórica.</p>
        </Descricao>
        <Imagem>https://www.gotokyo.org/en/plan/tokyo-outline/images/main.jpg</Imagem>
    </Lugar>

    <Lugar>
        <NomeLugar>Kyoto</NomeLugar>
        <Descricao>
            Kyoto, a antiga capital do Japão, foi fundada no ano de 794 e serviu como a capital imperial por mais de mil anos. É um tesouro de templos, santuários e tradições preservadas. Passeie pelas ruas de Gion, explore o Fushimi Inari Taisha com seus milhares de torii vermelhos e participe de uma cerimônia do chá em meio aos jardins zen.
            <p>Desfrute da atmosfera tranquila de bairros como Higashiyama, onde as ruas de paralelepípedos e as casas de chá tradicionais transportam você de volta no tempo.</p>
        </Descricao>
        <Imagem>https://media.cntraveler.com/photos/591dd1f2452a0b1d1cfbec51/16:9/w_2560%2Cc_limit/GettyImages-477329063.jpg</Imagem>
    </Lugar>

    <Lugar>
        <NomeLugar>Monte Fuji</NomeLugar>
        <Descricao>
            O Monte Fuji é uma montanha icônica do Japão, uma maravilha natural que se destaca majestosamente na paisagem. Com uma altura de 3.776 metros, o Monte Fuji é o pico mais alto do Japão e uma presença sagrada na cultura japonesa. Sua forma cônica perfeita é muitas vezes adornada com neve, criando uma visão deslumbrante.
            <p>Os visitantes têm a oportunidade de subir o Monte Fuji durante a temporada de escalada, que geralmente ocorre de julho a setembro. A vista do topo é espetacular, oferecendo panoramas expansivos das paisagens circundantes.</p>
        </Descricao>
        <Imagem>https://coisasdojapao.com/wp-content/uploads/2018/01/monte-fuji-7.webp</Imagem>
    </Lugar>

    <Lugar>
        <NomeLugar>Hiroshima e Miyajima</NomeLugar>
        <Descricao>
            Hiroshima é conhecida por sua resiliência após os eventos históricos da Segunda Guerra Mundial. Fundada no século XVI, a cidade é agora um símbolo de paz e reconciliação. Visite o Parque Memorial da Paz e a Ilha Miyajima, onde o famoso Torii Flutuante de Itsukushima é uma atração icônica.
            <p>Além de sua história tocante, Hiroshima oferece uma mistura de cultura, gastronomia e paisagens deslumbrantes.</p>
        </Descricao>
        <Imagem>https://www.princehotels.com/hiroshima/wp-content/uploads/sites/19/2019/07/miyajima-2-grand-prince-hotel-hiroshima.jpg</Imagem>
    </Lugar>

    <Lugar>
        <NomeLugar>Osaka</NomeLugar>
        <Descricao>
            Osaka é uma metrópole vibrante conhecida por sua culinária deliciosa, vida noturna agitada e a famosa área de entretenimento em Dotonbori. Fundada no século V, Osaka tornou-se um importante centro comercial durante o período Edo. Explore o majestoso Castelo de Osaka e experimente pratos locais como okonomiyaki e takoyaki.
            <p>Além da modernidade, Osaka preserva tradições culturais, proporcionando uma experiência única aos visitantes.</p>
        </Descricao>
        <Imagem>https://i0.wp.com/melhoresmomentosdavida.com/wp-content/uploads/2023/02/o-que-fazer-em-Osaka-1.jpg</Imagem>
    </Lugar>
</japao>
